name: release

on:
  workflow_dispatch:
  push:
    # Avoid duplicate builds on PRs.
    branches:
      - main
  pull_request:


jobs:
  release:    
      runs-on: ubuntu-22.04
      steps:
            - name: Install git lfs
              run: wget https://packagecloud.io/github/git-lfs/packages/debian/bullseye/git-lfs_3.3.0_amd64.deb/download -O git-lfs_3.3.0_amd64.deb
            - run: ls
            - run: sudo apt-get install ./git-lfs_3.3.0_amd64.deb
            - run: git lfs install
            - name: Checkout
              uses: actions/checkout@v3
              with:
                path: 'repo'
            - name: Checkout
              uses: actions/checkout@v3
              with:
                path: 'repo' 
            - uses: sudosubin/git-clone-action@v1.0.1
              with:
                repository: 'NicoAs/heroku-buildpack-python'
                path: 'repo/target'
            - run: ls -al repo
            - run: |
                cd repo
                tar cvz --exclude-vcs --exclude=python-3-11-1.tar.gz -f ../python-heroku-v${{ github.run_number}}.tar.gz . 
                cd ..
                ls
            - name: Create GitHub Release
              uses: actions/create-release@v1
              env:
                 GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: v${{ github.run_number}}
                release_name: Release v${{ github.run_number}}
            - name: Upload asset to GitHub Release
              uses: softprops/action-gh-release@v1
              with:
                files: python-heroku-v${{ github.run_number}}.tar.gz
                tag_name: v${{ github.run_number}}
            - name: Upload python to GitHub Release
              uses: softprops/action-gh-release@v1
              with:
                files: repo/python-3-11-1.tar.gz
                tag_name: v${{ github.run_number}}
        
